-- insert into inventory values(id, name, par_qty, on_hand_qty);
insert into inventory values(0,"Ground Beef",0,0);
insert into inventory values(1,"Ground Pork",0,0);
insert into inventory values(2,"Lasagna Noodles",0,0);
insert into inventory values(3,"ricotta",0,0);
insert into inventory values(4,"shredded mozerella",0,0);
insert into inventory values(5,"canned crushed tommatos",0,0);
insert into inventory values(6,"chicken breast",0,0);
insert into inventory values(7,"soy sauce",0,0);
insert into inventory values(8,"brown sugar",0,0);
insert into inventory values(9,"water",0,0);
insert into inventory values(10,"red pepper flakes",0,0);
insert into inventory values(11,"garlic powder",0,0);
insert into inventory values(12,"mustard powder",0,0);
insert into inventory values(13,"ginger powder",0,0);
insert into inventory values(14,"black pepper",0,0);
insert into inventory values(15,"sesemae seed oil",0,0);
