-- insert into ingredient values(recipe_id, inventory_id, sequence, adjective, quantity, partial_quantity, uom);
insert into ingredient values(0,0,0,"",1,"","POUND");
insert into ingredient values(0,1,1,"",1,"","POUND");
insert into ingredient values(0,2,2,"",12,"","OUNCE");
insert into ingredient values(0,3,3,"",15,"","OUNCE");
insert into ingredient values(0,4,4,"",2,"","CUP");
insert into ingredient values(0,5,5,"",28,"","OUNCE");
insert into ingredient values(2,6,0,"cubed",1,"ONE_HALF","POUND");
insert into ingredient values(2,7,1,"",0,"THREE_QUARTERS","CUP");
insert into ingredient values(2,8,2,"",0,"ONE_THIRD","CUP");
insert into ingredient values(2,9,3,"",0,"ONE_HALF","CUP");
insert into ingredient values(2,10,4,"",0,"ONE_HALF","TEASPOON");
insert into ingredient values(2,11,5,"",2,"","TEASPOON");
insert into ingredient values(2,12,6,"",1,"","TEASPOON");
insert into ingredient values(2,13,7,"",1,"","TEASPOON");
insert into ingredient values(2,14,8,"",1,"","TEASPOON");
insert into ingredient values(2,15,9,"",2,"","TEASPOON");
